import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/ui/sidebar";
import Searchbar from "@/components/ui/searchbar";
import { ToastContainer } from "react-toastify";
import ClientWrapper from "@/components/wrapper/ClientWrapper";

export const metadata: Metadata = {
  title: "hotster clone with next js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientWrapper>
        <body className={` flex items-center md:flex-row flex-col lg:px-[2%]`}>
          <ToastContainer
            autoClose={2}
            limit={3}
            newestOnTop
            position="top-right"
          />
          <Sidebar />
          <main className="w-full min-h-screen px-4 mb-10">
            <Searchbar />
            {children}
          </main>
        </body>
      </ClientWrapper>
    </html>
  );
}
