import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/ui/sidebar";
import Searchbar from "@/components/ui/searchbar";
import { ToastContainer } from "react-toastify";
// import ClientWrapper from "@/components/wrapper/ClientWrapper";

export const metadata: Metadata = {
  title: "hotster clone with next js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <ClientWrapper> */}
      <body
        className={` flex items-start md:flex-row flex-col lg:px-[2%]`}
      >
        <Sidebar />
        <main className="w-full min-h-screen ">
          <ToastContainer
            autoClose={2}
            limit={3}
            newestOnTop
            position="top-right"
          />
          <Searchbar />
          <div className="px-[2%]">{children}</div>
        </main>
      </body>
      {/* </ClientWrapper> */}
    </html>
  );
}
