import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/ui/sidebar";
import Searchbar from "@/components/ui/searchbar";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "hotster clone with next js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={` flex items-center md:flex-row flex-col lg:px-[2%]`}>
          <Sidebar />
          <div className="w-full min-h-screen px-4 mb-10">
            <Searchbar />
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
